# Generated by Django 5.1.4 on 2025-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
